apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-staging-test
  namespace: prod
spec:
  project: default
  source:
    repoURL: https://github.com/Binay-Basnet/ArgoCd.git
    targetRevision: main  # Specify the branch you want to use, e.g., "test"
    path: dev
  destination:
    server:  https://0.0.0.0:44109
    namespace: prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
# this is used is self heal l
    automated:
      selfHeal: true


